services:
  my-postgres:
    image: jderobot/bt-studio-database:latest
    container_name: universe_db
    environment:
      POSTGRES_DB: universe_db
      POSTGRES_USER: user-dev
      POSTGRES_PASSWORD: bt-studio-dev
    ports:
      - "5432:5432"
    volumes:
      - ./RoboticsInfrastructure/database/universes.sql:/docker-entrypoint-initdb.d/1.sql
      - ./backend/django_auth.sql:/docker-entrypoint-initdb.d/2.sql
      - ./backend/database/db.sql:/docker-entrypoint-initdb.d/3.sql
    healthcheck:
      test: pg_isready -U user-dev -d universe_db
      interval: 3s
      timeout: 1s
      retries: 20

  bt-studio:
    image: jderobot/bt-studio:latest
    container_name: developer-container
    command: "-bt"
    ports:
      - "7164:7164"
      - "7163:7163"
      - "6080-6090:6080-6090"
    volumes:
      - type: bind
        source: ./
        target: /BtStudio
    tty: true
    stdin_open: true
    depends_on:
      my-postgres:
        condition: service_healthy
