services:
  my-postgres:
    image: jderobot/bt-studio-database:latest
    container_name: universe_db
    environment:
      POSTGRES_DB: universe_db 
      POSTGRES_USER: user-dev 
      POSTGRES_PASSWORD: bt-studio-dev
    ports:
      - "5432:5432"
    volumes:
      - ./RoboticsInfrastructure/database/universes.sql:/docker-entrypoint-initdb.d/1.sql
      - ./backend/django_auth.sql:/docker-entrypoint-initdb.d/2.sql
    healthcheck:
      test: pg_isready -U user-dev -d universe_db
      interval: 3s
      timeout: 1s
      retries: 20

  bt-studio:
    image: jderobot/robotics-backend:latest
    container_name: developer-container
    command:  "-bt"
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - "7164:7164"
      - "7163:7163"
      - "6080:6080"
      - "1108:1108"
    volumes:
      - type: bind
        source: ./
        target: /BtStudio
    tty: true
    stdin_open: true
    depends_on: 
      my-postgres:
        condition: service_healthy
