# Generates and uploads an image of BT-Studio using the desired tag and branches
name: Generate tagged BT-Studio image

on:
  workflow_call:
    inputs:
      tag:
        description: 'Docker Image Tag'
        required: true
        default: test
        type: string
      latest:
        description: 'Upload as latest'
        required: true
        default: false
        type: boolean
      BT:
        description: 'Branch of BT-Studio'
        required: true
        default: main
        type: string
      RI:
        description: 'Branch of Robotics Infrastructure'
        required: true
        default: humble-devel
        type: string
      RAM:
        description: 'Branch of Robotics Application Manager'
        required: true
        default: humble-devel
        type: string
      ROS:
        description: 'ROS Distro (humble)'
        required: true
        default: humble
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Image Tag'
        required: true
        default: test
        type: string
      latest:
        description: 'Upload as latest'
        required: true
        default: false
        type: boolean
      BT:
        description: 'Branch of BT-Studio'
        required: true
        default: main
        type: string
      RI:
        description: 'Branch of Robotics Infrastructure'
        required: true
        default: humble-devel
        type: string
      RAM:
        description: 'Branch of Robotics Application Manager'
        required: true
        default: humble-devel
        type: string
      ROS:
        description: 'ROS Distro (humble)'
        required: true
        default: humble
        type: string

jobs:
  push_to_registry:
    name: Run Test and Update Docker Image
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.tag }}
    steps:
      - name: Save the version tag
        run: echo "TAG=${TAG#v}" >> $GITHUB_ENV
      - name: Free disk space
        run: curl -fsSL https://raw.githubusercontent.com/kou/arrow/e49d8ae15583ceff03237571569099a6ad62be32/ci/scripts/util_free_space.sh | bash
      - name: Check out the repo # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch-webserver-id }}
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build base image
        run: |
          sudo apt-get update
          cd scripts/BTDI
          if [ "${{ github.event.inputs.ROS }}" == "humble" ]; then
            docker build -f Dockerfile.dependencies_humble -t jderobot/robotics-applications:dependencies-humble .
          else
            echo "Incorrect ROS version"
          fi
      - name: Build and push BTDI
        run: |
          cd scripts/BTDI
          if [ "${{ github.event.inputs.ROS }}" == "humble" ]; then
            docker build --no-cache -f Dockerfile.humble \
              --build-arg BT_STUDIO=${{ github.event.inputs.BT }}\
              --build-arg ROBOTICS_INFRASTRUCTURE=${{ github.event.inputs.RI }} \
              --build-arg RAM=${{ github.event.inputs.RAM }} \
              --build-arg ROS_DISTRO=${{ github.event.inputs.ROS }} \
              --build-arg IMAGE_TAG=${TAG} \
              -t jderobot/bt-studio:${TAG} .
            docker push jderobot/bt-studio:${TAG}
          else
            echo "Incorrect ROS version"
          fi
      - name: Upload as Latest
        if:  ${{ inputs.latest }} 
        run: |
            docker image tag jderobot/bt-studio:${TAG} jderobot/bt-studio:latest
            docker push jderobot/bt-studio:latest