# Generates and uploads an image of Bt-Studio and Bt-Studio database using the desired tag and branches
name: Release new Bt Studio Version on new version

on:
  release:
    types: [published]

jobs:
  printed:
    name: Save the version tag
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.event.release.tag_name: ${{ github.event.release.tag_name }}"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
  generate-Bt-Studio-docker-image:
    name: Generate Bt-Studio Image
    uses: ./.github/workflows/generate_Bt_Studio.yml
    with:
      tag: $GITHUB_REF_NAME
      latest: true
      BT: main
      RI: humble-devel
      RAM: humble-devel
      ROS: humble
    secrets: inherit
  generate-Bt-Studio-database-docker-image:
    name: Generate Bt-Studio Database Image
    uses: ./.github/workflows/generate_Bt_Studio_Database.yml
    with:
      tag: $GITHUB_REF_NAME
      latest: true
      BT: main
      RI: database
    secrets: inherit
