# Generates and uploads an image of Bt-Studio and Bt-Studio database using the desired tag and branches
name: Release new Bt Studio Version Manually

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Image Tag'
        required: true
        default: test
      latest:
        description: 'Upload as latest'
        required: true
        default: true
        type: boolean
      BT:
        description: 'Branch of BT-Studio'
        required: true
        default: main
      RI:
        description: 'Branch of Robotics Infrastructure'
        required: true
        default: humble-devel
      RIDB:
        description: 'Branch of Robotics Infrastructure for Universes Database'
        required: true
        default: database
      RAM:
        description: 'Branch of Robotics Application Manager'
        required: true
        default: humble-devel
      ROS:
        description: 'ROS Distro (humble)'
        required: true
        default: humble

jobs:
  generate-Bt-Studio-docker-image:
    name: Generate Bt-Studio Image
    uses: ./.github/workflows/generate_Bt_Studio.yml
    with:
      tag: ${{ github.event.inputs.tag }}
      latest: ${{ inputs.latest }}
      BT: ${{ github.event.inputs.BT }}
      RI: ${{ github.event.inputs.RI }}
      RAM: ${{ github.event.inputs.RAM }}
      ROS: ${{ github.event.inputs.ROS }}
    secrets: inherit
  generate-Bt-Studio-database-docker-image:
    name: Generate Bt-Studio Database Image
    uses: ./.github/workflows/generate_Bt_Studio_Database.yml
    with:
      tag: ${{ github.event.inputs.tag }}
      latest: ${{ inputs.latest }}
      BT: ${{ github.event.inputs.BT }}
      RI: ${{ github.event.inputs.RIDB }}
    secrets: inherit