# Generates and uploads an image of Bt-Studio and Bt-Studio database using the desired tag and branches
name: Release new Bt Studio Version on new version

on:
  release:
    types: [published]

jobs:
  generate-Bt-Studio-docker-image:
    name: Generate Bt-Studio Image
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.release.tag_name }}
    steps:
      - name: Save the version tag
        run: echo "TAG=${TAG#v}" >> $GITHUB_ENV
      - name: Check out the repo # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch-webserver-id }}
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build base image
        run: |
          sudo apt-get update
          cd scripts/BTDI
          docker build -f Dockerfile.dependencies_humble -t jderobot/robotics-applications:dependencies-humble .
      - name: Build and push BTDI
        run: |
          cd scripts/BTDI
          docker build --no-cache -f Dockerfile.humble \
            --build-arg BT_STUDIO=main\
            --build-arg ROBOTICS_INFRASTRUCTURE=humble-devel\
            --build-arg RAM=humble-devel \
            --build-arg ROS_DISTRO=humble \
            --build-arg IMAGE_TAG=${TAG} \
            -t jderobot/bt-studio:${TAG} .
          docker push jderobot/bt-studio:${TAG}
      - name: Upload as Latest
        run: |
            docker image tag jderobot/bt-studio:${TAG} jderobot/bt-studio:latest
            docker push jderobot/bt-studio:latest
  generate-Bt-Studio-database-docker-image:
    name: Generate Bt-Studio Database Image
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.release.tag_name }}
    steps:
      - name: Save the version tag
        run: echo "TAG=${TAG#v}" >> $GITHUB_ENV
      - name: Check out the repo # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch-webserver-id }}
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Bt Studio database
        run: |
          cd scripts/BTDI
          docker build --no-cache -f Dockerfile.database \
            --build-arg IMAGE_TAG=${TAG} \
            --build-arg BT_STUDIO=main\
            --build-arg ROBOTICS_INFRASTRUCTURE=database \
            -t jderobot/bt-studio-database:${TAG} .
          docker push jderobot/bt-studio-database:${TAG}
      - name: Upload as Latest
        run: |
            docker image tag jderobot/bt-studio-database:${TAG} jderobot/bt-studio-database:latest
            docker push jderobot/bt-studio-database:latest
