# Generates and uploads an image of Bt-Studio and Bt-Studio database using the desired tag and branches
name: Release new Bt Studio Version

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker Image Tag'
        required: true
        default: v1.1.1

jobs:
  generate-Bt-Studio-docker-image:
    name: Generate Bt-Studio Image
    uses: ./.github/workflows/generate_Bt_Studio.yml
    with:
      tag: ${{ github.event.inputs.tag }}
      latest: false
      BT: main
      RI: humble-devel
      RAM: humble-devel
      ROS: humble
    secrets: inherit